version: '3'
services:
   backend:
     build: backend/.
     ports:
       - 8080:8080
     depends_on:
       - database
     restart: on-failure

   database:
    image: mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
